#
# Copyright (C) 2015 OpenTravel Alliance (info@opentravel.org)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

CREATE TABLE REGISTRANT (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	LAST_NAME VARCHAR(50) NOT NULL,
	FIRST_NAME VARCHAR(50) NOT NULL,
	COMPANY VARCHAR(100),
	TITLE VARCHAR(100),
	EMAIL VARCHAR(50) NOT NULL,
	PHONE VARCHAR(50),
	OTA_MEMBER BOOLEAN NOT NULL DEFAULT 0,
	REGISTRATION_DATE DATE,
	PRIMARY KEY (ID)
);

CREATE TABLE FILE_CONTENT (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	FILE_BYTES LONGBLOB NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE PUBLICATION (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(50) NOT NULL,
	PUB_TYPE VARCHAR(20) NOT NULL,
	PUB_STATE VARCHAR(20) NOT NULL,
	PUB_DATE TIMESTAMP NOT NULL,
	ARCHIVE_FILENAME VARCHAR(50) NOT NULL,
	ARCHIVE_CONTENT_ID BIGINT NOT NULL,
	RELEASE_NOTES_FILENAME VARCHAR(50) NOT NULL,
	RELEASE_NOTES_CONTENT_ID BIGINT NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (ARCHIVE_CONTENT_ID) REFERENCES FILE_CONTENT(ID),
	FOREIGN KEY (RELEASE_NOTES_CONTENT_ID) REFERENCES FILE_CONTENT(ID)
);

CREATE TABLE PUBLICATION_GROUP (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	PUBLICATION_ID BIGINT NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	MEMBER_TYPE VARCHAR(20) NOT NULL,
	SORT_ORDER INT NOT NULL,
	REMOVED BOOLEAN NOT NULL DEFAULT 0,
	PRIMARY KEY (ID),
	FOREIGN KEY (PUBLICATION_ID) REFERENCES PUBLICATION(ID)
);

CREATE TABLE PUBLICATION_ITEM (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	GROUP_ID BIGINT NOT NULL,
	ITEM_TYPE VARCHAR(20) NOT NULL,
	ITEM_FILENAME VARCHAR(50) NOT NULL,
	ITEM_CONTENT_ID BIGINT NOT NULL,
	FILE_SIZE BIGINT NOT NULL,
	CREATE_DATE TIMESTAMP NOT NULL,
	REMOVED BOOLEAN NOT NULL DEFAULT 0,
	PRIMARY KEY (ID),
	FOREIGN KEY (GROUP_ID) REFERENCES PUBLICATION_GROUP(ID),
	FOREIGN KEY (ITEM_CONTENT_ID) REFERENCES FILE_CONTENT(ID)
);

CREATE TABLE COMMENT (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	COMMENT_NUMBER INT NOT NULL,
	PUBLICATION_ITEM_ID BIGINT,
	OTHER_ITEM_NAME VARCHAR(200),
	PUB_STATE VARCHAR(20) NOT NULL,
	REGISTRANT_ID BIGINT NOT NULL,
	COMMENT_TYPE VARCHAR(20) NOT NULL,
	COMMENT_TEXT TEXT NOT NULL,
	SUGGESTED_CHANGE TEXT NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (PUBLICATION_ITEM_ID) REFERENCES PUBLICATION_ITEM(ID),
	FOREIGN KEY (REGISTRANT_ID) REFERENCES REGISTRANT(ID)
);

CREATE TABLE SCHEMA_COMMENT (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	COMMENT_XPATH VARCHAR(200) NOT NULL,
	MODIFY_XPATH VARCHAR(200) NOT NULL,
	NEW_ANNOTATIONS TEXT NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE ARTIFACT_COMMENT (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	PAGE_NUMBERS VARCHAR(100) NOT NULL,
	LINE_NUMBERS VARCHAR(100) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE COMMENT_COUNTER (
	NEXT_VAL INT NOT NULL
);

CREATE TABLE PUBLICATION_DOWNLOAD (
	PUBLICATION_ID BIGINT NOT NULL,
	REGISTRANT_ID BIGINT NOT NULL,
	PRIMARY KEY (PUBLICATION_ID, REGISTRANT_ID),
	FOREIGN KEY (PUBLICATION_ID) REFERENCES PUBLICATION(ID),
	FOREIGN KEY (REGISTRANT_ID) REFERENCES REGISTRANT(ID)
);

CREATE TABLE PUBLICATION_ITEM_DOWNLOAD (
	PUBLICATION_ITEM_ID BIGINT NOT NULL,
	REGISTRANT_ID BIGINT NOT NULL,
	PRIMARY KEY (PUBLICATION_ITEM_ID, REGISTRANT_ID),
	FOREIGN KEY (PUBLICATION_ITEM_ID) REFERENCES PUBLICATION_ITEM(ID),
	FOREIGN KEY (REGISTRANT_ID) REFERENCES REGISTRANT(ID)
);

CREATE TABLE USERS (
	USERNAME VARCHAR(50) NOT NULL,
	PASSWORD VARCHAR(50) NOT NULL
);

CREATE TABLE USER_ROLES (
	USERNAME VARCHAR(50) NOT NULL,
	ROLENAME VARCHAR(50) NOT NULL
);

# Default userid/password = admin/admin
INSERT INTO USERS VALUES ("admin", "d033e22ae348aeb5660fc2140aec35850c4da997");
INSERT INTO USER_ROLES VALUES ("admin", "administrators");
